% Code to produce efficiency plot algorithms

function timeerror_plot_ekinetics(step,Error_mat)
% INPUT: Time_mat is matrix whose rows correspond to the time values of
% each algorithm
%        Error_mat is a matrix whose rows correspond to the error values of
%        each algorithm. Must be the same size as Time_mat

%% Extract Data

% Extract Error
error1= Error_mat(1,:);
error2= Error_mat(2,:);
error3= Error_mat(3,:);
error4= Error_mat(4,:);

% error6= Error_mat(6,:);
% error7= Error_mat(7,:);


%% Produce Plots
figure
set(0,'defaultaxesfontsize',12)
loglog(step,error1,'sb-',...
    'LineWidth',2.5,...
    'MarkerSize',10)
 hold on
loglog(step,error2,'o-','color',[0 0.5 0.2],...
    'LineWidth',2.5,...
    'MarkerSize',10)
loglog(step,error3,'pr-',...
    'LineWidth',2.5,...
    'MarkerSize',10)
loglog(step,error4,'^k-',...
    'LineWidth',2.5,...
    'MarkerSize',10)
% loglog(step,error5,'sg-',...
%     'LineWidth',2,...
%     'MarkerSize',8)
% semilogy(step,error6,'--rs',...
%     'LineWidth',3,...
%     'MarkerSize',5,...
%     'MarkerEdgeColor','k',...
%     'MarkerFaceColor','r')
% semilogy(step,error7,'--ms',...
%     'LineWidth',3,...
%     'MarkerSize',5,...
%     'MarkerEdgeColor','k',...
%     'MarkerFaceColor','m')
grid on
legend('ETDRDP','ETDRCN','ETDP02','BDF2')

xlabel('\bf\fontsize{12} Time Step')
ylabel('\bf\fontsize{12} Error')




